/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: HoangHiepVu (https://sketchfab.com/HoangHiepVu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/korean-gate-jardin-dacclimatation-paris-d46dbd1b79b142a6a8a499d629c43f1d
Title: Korean Gate , Jardin d'Acclimatation, Paris
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Korean(props) {
  const { nodes, materials } = useGLTF('./models/korean/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.057, 7.943]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.material_2}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/korean/scene.gltf')


