/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: heddathunell (https://sketchfab.com/heddathunell)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butterfly-bb7a9781c2674e59a0f335fb8efb77d3
Title: Butterfly
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Butterfly(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/butterfly/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {

    actions.Object_0.play();
    actions.Object_0.timeScale=0.22
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="913812325ebb4106b80eca412a29f029abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group
                  name="Object_4"
                  position={[2.473, -1.185, 1.224]}
                  rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="TimeframeMainGroup">
                    <group name="Object_6">
                      <mesh
                        name="Box001_2_0"
                        castShadow
                        receiveShadow
                        geometry={nodes.Box001_2_0.geometry}
                        material={materials.Box001}
                      />
                    </group>
                  </group>
                  <group name="Object_8" position={[0.144, -1.17, 1.185]}>
                    <group name="Object_9" position={[29.774, 0.869, 0]}>
                      <group name="MorphMainGroup">
                        <mesh
                          name="Line001"
                          castShadow
                          receiveShadow
                          geometry={nodes.Line001.geometry}
                          material={materials.Line001}
                          morphTargetDictionary={nodes.Line001.morphTargetDictionary}
                          morphTargetInfluences={nodes.Line001.morphTargetInfluences}
                        />
                      </group>
                      <group name="MorphMainGroup_1">
                        <mesh
                          name="Line001_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.Line001_1.geometry}
                          material={materials.Line001}
                          morphTargetDictionary={nodes.Line001_1.morphTargetDictionary}
                          morphTargetInfluences={nodes.Line001_1.morphTargetInfluences}
                        />
                      </group>
                    </group>
               
                  </group>
                  <group name="Object_19" position={[0.128, -1.891, 1.185]}>
                    <group name="Object_20" position={[-31.618, -4.184, 0]}>
                      <group name="MorphMainGroup_4">
                        <mesh
                          name="Line004"
                          castShadow
                          receiveShadow
                          geometry={nodes.Line004.geometry}
                          material={materials.Line004}
                          morphTargetDictionary={nodes.Line004.morphTargetDictionary}
                          morphTargetInfluences={nodes.Line004.morphTargetInfluences}
                        />
                      </group>
                      <group name="MorphMainGroup_5">
                        <mesh
                          name="Line004_1"
                          castShadow
                          receiveShadow
                          geometry={nodes.Line004_1.geometry}
                          material={materials.Line004}
                          morphTargetDictionary={nodes.Line004_1.morphTargetDictionary}
                          morphTargetInfluences={nodes.Line004_1.morphTargetInfluences}
                        />
                      </group>
                    </group>
                   
                  </group>
              
            
                  <group name="TimeframeMainGroup_17">
                  
                  </group>
                </group>
            
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/butterfly/scene.gltf')
