/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [3.18KB] > C:\Users\jjy83\sLang\frontend\slang\public\models\flower_2\scene-transformed.glb [10.18KB] (-220%)
Author: Michelle.Q (https://sketchfab.com/Michelle.Q)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lily-flower-e41a69403707405dbb5e0b7737cae6fa
Title: Lily Flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower_2(props) {
  const { nodes, materials } = useGLTF('./models/flower_2/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/flower_2/scene-transformed.glb')
