/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [13.99KB] > C:\Users\jjy83\sLang\frontend\slang\public\models\flower_4\scene-transformed.glb [75.89KB] (-442%)
Author: shockeova (https://sketchfab.com/shockeova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-1cdf9df6b941460bb70b7758c9e416ec
Title: Flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower_4(props) {
  const { nodes, materials } = useGLTF('./models/flower_4/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pPlane2_lambert2_0.geometry} material={materials.lambert2} position={[5, 2.072, -5]} />
      <instancedMesh args={[nodes.pPlane1_lambert2_0.geometry, materials.lambert2, 5]} instanceMatrix={nodes.pPlane1_lambert2_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('./models/flower_4/scene-transformed.glb')
