/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [31.16KB] > C:\Users\jjy83\sLang\frontend\slang\public\models\flower\scene-transformed.glb [101.27KB] (-225%)
Author: ratbags (https://sketchfab.com/ratbags)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-flower-b75df2333b914f529058134e9e3fadac
Title: Alien Flower
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower(props) {
  const { nodes, materials } = useGLTF('./models/flower/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pPlane4_lambert6_0.geometry} material={materials.lambert6} rotation={[-1.379, -1.519, -1.347]} />
      <mesh geometry={nodes.pPlane8_lambert5_0.geometry} material={materials.lambert5} rotation={[2.621, -0.604, -3.131]} scale={0.671} />
      <instancedMesh args={[nodes.pSphere6_lambert7_0.geometry, materials.lambert7, 6]} instanceMatrix={nodes.pSphere6_lambert7_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('./public/models/flower/scene-transformed.glb')
