/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alexandra.m.neville (https://sketchfab.com/alexandra.m.neville)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-flower-loop-a9d02b903a494b60906d44d0c855f7a3
Title: Simple Flower Loop
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Flower_2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/flower_2/scene.gltf')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    actions.Object_0.play();
    actions.Object_0.timeScale=0.15
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[-0.011, 0.036, -0.044]}
          rotation={[-0.039, 0.372, -1.557]}
          scale={3.387}>
          <group name="d9519426e61142ddacee8e1492ac5ef6abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="MorphMainGroup">
                  <mesh
                    name="timeshift4"
                    castShadow
                    receiveShadow
                    geometry={nodes.timeshift4.geometry}
                    material={materials.timeshift4}
                    morphTargetDictionary={nodes.timeshift4.morphTargetDictionary}
                    morphTargetInfluences={nodes.timeshift4.morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/flower_2/scene.gltf')