/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [19.1KB] > C:\Users\jjy83\sLang\frontend\slang\public\models\flower_3\scene-transformed.glb [2.71MB] (-14080%)
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/cc0-rip-my-friend-abc1bba2bdac40d0acff87d52a3aa0a7
Title: CC0 | RIP My Friend
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower_3(props) {
  const { nodes, materials } = useGLTF('./models/flower_3/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['MRKT058-W01-1-1.001']} />
    </group>
  )
}

useGLTF.preload('./models/flower_3/scene-transformed.glb')
