/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: renderpunk (https://sketchfab.com/renderpunk)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/korean-lion-statue-scan-f72ce3251d7c468ab68ea32e681b8f1d
Title: Korean Lion Statue Scan
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Haetae(props) {
  const { nodes, materials } = useGLTF('./models/haetae/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Default_OBJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.Default_OBJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Default_OBJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.Default_OBJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.Default_OBJ}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.Default_OBJ}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/haetae/scene.gltf')


