/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Korea Craft & Design Foundation (https://sketchfab.com/KCDF)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kcdf-window-blind-hangul-01-d4389811ba09400096518a4b7bb228e7
Title: KCDF-Window Blind_Hangul_01
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Hanguel2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/hanguel/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Tradition_Blind_Hanbokfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.M_Bla_Hangle}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.M_Frame}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <group name="Object_6" position={[7551.908, 7108.921, 0]} />
                  <group name="Tradition_Blind_Hangle" position={[7551.908, 7108.921, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/hanguel/scene.gltf')


